#!/bin/sh

declare -a cydia
cydia=($CYDIA)

if [[ $1 == remove ]]; then
    if [[ ${CYDIA+@} ]]; then
        eval "echo 'finish:restart' >&${cydia[0]}"
    fi

    grep -v ' com\.saurik\.winterboard\.' /etc/notify.conf >/etc/notify.conf_ &&
        chmod --reference=/etc/notify.conf /etc/notify.conf_ &&
        chown --reference=/etc/notify.conf /etc/notify.conf_ &&
        mv -f /etc/notify.conf{_,} || rm -f /etc/notify.conf_
fi

exit 0
